#!/bin/bash

shopt -s extglob
laa() {
    if [[ $# -eq 1 ]]; then
        exec 3>&1   # This creates another writing file descriptor that points to STDOUT in this shell
        _items=$(cd ${1}; ls -d .!(|.)?* 1>&3)  # This requires extended glob
                                                # `shopt -s extglob` to enable
        unset _items
        exec 3>&- # Closes the writing file descriptor
    elif [[ $# -gt 1 ]]; then
        exec 3>&1
        for i in $@; do
            _items=$(cd $i; echo "$i:" 1>&3; ls -d .!(|.)* 1>&3)
        done
        unset _items i
        exec 3>&-
    else
        ls -d .!(|.)*
    fi

}